cli.js

I have refactored the code to replace multiple "if" by an Object with arrow function.
When we run the cli without args, it will run the commit command.
If args are invalid, the help will be displayed.
Issue: #11

Fix default behaviour and display help if invalid args

---

src/gitmoji.js

It seems that with fs.writeFile, the mode option needs to be specified as an octal number. I determined this after running `gitmoji -i`, and having the file created with very strange permissions:
```
$ stat .git/hooks/prepare-commit-msg
File: '.git/hooks/prepare-commit-msg'
Size: 70        	Blocks: 8          IO Block: 4096   regular file
Device: fd03h/64771d	Inode: 19398811    Links: 1
Access: (1361/--wxrw---t)  Uid: ( 1000/  grdryn)   Gid: ( 1000/  grdryn)
Context: unconfined_u:object_r:container_file_t:s0
Access: 2016-11-26 02:19:14.661093296 +0000
Modify: 2016-11-26 02:19:14.661093296 +0000
Change: 2016-11-26 02:19:14.661093296 +0000
Birth: -
```
The docs[1] for this function give the default example as being in octal, and when I changed it and tried it out, it worked much better.
In …

🐛  Fix access mode of prepare-commit-msg

---

cli.js
src/gitmoji.js

Gitmoji caches a remote request to emoji list in `HOME/.gitmoji/gitmojis.json`. You can sync with Gitmoji repository manually by `gitmoji -u` command.
Issue: #1

Adds an offline capability

---

src/gitmoji.js

If auto add is disabled, the user will receive an empty error message when trying to commit unstaged changes. Although auto add is enabled by default now, there are cases where it will be disabled and then a user will receive an empty `ERROR:` message.
Issue: https://github.com/carloscuesta/gitmoji-cli/issues/39
**Previous behavior**
```sh
❯ ./cli.js
? Choose a gitmoji: 🎨  - Improving structure / format of the code.
? Enter the commit title: 123
? Enter the commit message: 123
? Issue / PR reference #:
? Signed commit: Yes
ERROR:
```
**New behavior**
```sh
❯ ./cli.js
? Choose a gitmoji: 🎨  - Improving structure / format of the code.
? Enter the commit title: foo
? Enter the commit message: bar
? Issue / PR reference #:
? Signed commit: Yes
ERROR: On branch master
Your branch is up-to-date …
```

Report stdout as error if stderr is empty

---

src/gitmoji.js
test/test.js

This pull request adds the ability to:
- Set a issue tracker format in the settings (defaults to github)
- Validate JIRA issue keys if issue tracker format is set to JIRA
- Remove the preceeding # if issue tracker format is set to JIRA
Go easy on me, it is my first attempt at node. I was thinking about a larger refactoring where the issue tracker is an object that encapsulates it's own rules and formatting, so like
```
class JIRAFormatter {
function getPrefix() {};
function isValid() {};
function getCommitTemplate() { // {issuekey} {summary} - {description} }
} 
class GithubFormatter {
function getPrefix() {};
function isValid() {}
function getCommitTemplate() { // {summary} - {description} {issuekey} }
}
```
... but I decided against it for the time being! Maybe another day.
All feedback …

Add jira reference support

---

src/gitmoji.js
test/test.js

I added back this feature I asked for along with the test case. I kept the `:smile:` format as the first option and also as the fallback case
Issue: #

:sparkles: Add emoji format to config

---

cli.js
src/gitmoji.js
test/test.js

Introduces the new command `--remove|-r` to unlink a previously set hook. Avoids having to dive into the .git dir in a terminal and remove it there. I love Gitmoji, but sometimes needed to remove it for projects where other people didn't want to use it.
It uses `fs#unlink` which is an async method that takes the path and a completion callback. Very much like `fs#writeFile`.

✨ Add possibility to remove hook

---

src/gitmoji.js

Use `fs.writeFile` and `process.exit()` at `_hook` method. This will prevent to freeze when using the hook option.

🐛 Use fs.writeFile and exit the process if success @ hook

---

src/gitmoji.js

When in hook mode, it can happen that we exit function and directly go to calling `_commit` BEFORE actually finishing `_hook` code.
This can be detected adding `console.log` statements to code and trying to commit different messages:
```
diff --git a/src/gitmoji.js b/src/gitmoji2.js
index 4e7809a..e9639a0 100644
--- a/src/gitmoji.js
+++ b/src/gitmoji2.js
@@ -127,11 +127,13 @@ class GitmojiCli {
return this._errorMessage(error)
}
+      console.log('_hook exited');
process.exit(0)
})
}
_commit (answers) {
+    console.log('_commit called');
const title = `${answers.gitmoji} ${answers.title}`
const prefixReference = config.getIssueFormat() === constants.GITHUB
? '#'
```
And here is the output of running modified gitmoji hook in the repo (commit was aborted intentionally):
```
➜ git commit …
```

🐛 Fix race-condition in hook mode

---

src/config.js
src/constants.js
src/gitmoji.js
src/prompts.js
test/__snapshots__/gitmojiCli.spec.js.snap
test/gitmojiCli.spec.js

Add an option to enable/disable the scope promt (asked here: https://github.com/carloscuesta/gitmoji-cli/issues/217).
By default the option is disabled to keep the current people workflow intact.

Option to enable/disable the scope promt

---

src/commands/config/index.js
src/commands/config/prompts.js
test/commands/config.spec.js

Set the current config values as default when using `gitmoji -g`.
This is very useful when you want to change a single value.

Set current values as default in `gitmoji -g`

---

src/utils/isHookCreated.js
test/utils/isHookCreated.spec.js

Prevents accidentally matching another hook (e.g. Husky) as a collision.

🐛 Check pre-commit-hook for contents

---

src/commands/hook/hook.js
test/commands/__snapshots__/hook.spec.js.snap

Ignore hook if not creating a _new_ commit, from a TTY
It solves and supersedes https://github.com/carloscuesta/gitmoji-cli/pull/112: Ignore hook when rebasing.

Ignore hook if not creating a new commit, from a TTY

---

package.json
src/commands/commit/prompts.js
src/commands/search/index.js
src/utils/filterGitmojis.js
src/utils/printEmojis.js
test/utils/filterGitmojis.spec.js
test/utils/stubs.js
yarn.lock

Use [fuzzy](https://www.npmjs.com/package/fuzzy) search.
This will for example make such a search possible:
Issue: #147

Add fuzzy search

---

src/utils/filterGitmojis.js
test/utils/filterGitmojis.spec.js
test/utils/stubs.js

This PR does 2 things:
- Add a lower `threshold` (from the `0.6` default to `0.5`) to the `Fuse.js` search options on the gitmojis to better match what the user is trying to get
- Improve the `filterGitmoji.spec.js` test suite to directly test the filter on real life use cases 
Issue: #302

🚸 Improve fuzzy search

---

src/commands/hook/hook.js
test/commands/__snapshots__/hook.spec.js.snap

The Bash hook script now iterates through all lines in the staged commit message file and checks if they are not empty. Lines below the snip - introduced when committing with the `--verbose` flag - are ignored, as they are ignored by Git and as such do not contribute to the commit message. 
Issue: #313

🐛 Commit hook skips prompt when using verbose flag (Closes #313)

---

src/utils/filterGitmojis.js
test/utils/filterGitmojis.spec.js

Version 3.6.0 of Fuse.js introduced an exception when the total weights of all the keys is > 1.
https://github.com/krisk/Fuse/commit/1fb86f0ebd8bba374d81ef4b8ffa8a296cd7898e#diff-1fdf421c05c1140f6d71444ea2b27638R137-R139
This PR updates the key weights to match the existing ratios, but with the total weight being 1. Additionally, a new test case exists to ensure the weights remain equal or under 1.
Issue: #324

🐛 Reduced sum of search weights to equal 1

---

src/commands/commit/index.js
src/commands/commit/withHook/index.js
test/commands/commit.spec.js

meow version update introduce a bug with the crl-c behavior of gitmoji: the commit is aborded instead of proceeding without gitmoji.
I pinned the version of meow to the last version without the bug.
Issue: #266

Fix hook abort with ctrl-c behavior to match v3.0.0

---

src/commands/commit/index.js
src/commands/commit/withHook/index.js
test/commands/commit.spec.js

Hi @carloscuesta ,
At first I just wanted to build end to end tests over @nathan818fr [pull request](https://github.com/carloscuesta/gitmoji-cli/pull/366). However there are numerous difficulties in doing a true E2E testing of a CLI app. The deal breaker for gitmoji being that inquirer doesn't handle piping to answer. I also tried to mock some libs like inquirer to avoid the prompt but still use a classic `git commit` flow to trigger the `prepare-commit-msg` hook without success.
My last idea was to use some remotely controllable terminal to deal with the interactivity of inquirer (similar in principle to cypress for web app), but except [kitty terminal](https://sw.kovidgoyal.net/kitty/#remote-control), I don't know another terminal that implement this feature and as kitty is still …

✨ Cancel hook when a git message is already set

---

src/utils/isHookCreated.js
test/utils/isHookCreated.spec.js

At #254 we introduced a bug where the function was not checking if the hook was created successfully. This PR fixes that utility.

Fix isHookCreated util

---

.gitignore
src/commands/commit/index.js
src/commands/commit/prompts.js
src/utils/getDefaultCommitContent.js
test/commands/__snapshots__/commit.spec.js.snap
test/commands/commit.spec.js
test/commands/stubs.js
test/utils/getDefaultCommitContent.spec.js

Hi @carloscuesta, this PR adds prefilling the `title` and `message` prompts when in `hook` mode.
This allows to keep your titles and messages in your history.

✨ Prefill title and message in hook mode

---

src/commands/commit/index.js
src/commands/commit/withHook/index.js
test/commands/commit.spec.js

Hi @carloscuesta, I recreated the feature to cancel the hook on rebase.
Noteworthy point, I contacted @adriencaccia, which implemented a elegant solution on a fork to prefill the commit message in this case, he will come back to you with a proposition .
Issue: https://github.com/carloscuesta/gitmoji-cli/issues/444

✨ Cancel hook on rebase

---

src/commands/commit/index.js
src/commands/commit/withHook/index.js
src/commands/hook/hook.js
test/commands/__snapshots__/hook.spec.js.snap
test/commands/commit.spec.js
test/commands/stubs.js

I implemented interruption of the hook on `git commit --amend` while investigation `yarn version` command. I recommand reading the linked issue for a more in depth summary of why `yarn release` is not compatible with gitmoji
Issue: linked to https://github.com/carloscuesta/gitmoji-cli/issues/497
- I added a test and fixed previous ones
ps: love the migration to github actions :heart:

Implement hook abord on amend

---

src/commands/commit/index.js
src/commands/commit/withHook/index.js
src/commands/hook/hook.js
test/commands/__snapshots__/hook.spec.js.snap
test/commands/commit.spec.js
test/commands/stubs.js

This reverts commit caf87bd5fbcdbac21b76ab06f58557811abb5469 (re-implement abord on amend) and
implement a fix for missing second hook param.
Issue: https://github.com/carloscuesta/gitmoji-cli/issues/509
- I added a test for undefined

✨ Implement hook abort on amend

---

src/commands/hook/create/index.js
src/commands/hook/hook.js
src/commands/hook/remove/index.js
src/utils/getAbsoluteHooksPath.js
src/utils/isHookCreated.js
test/commands/__snapshots__/hook.spec.js.snap
test/commands/hook.spec.js
test/commands/stubs.js
test/setupTests.js
test/utils/getAbsoluteHooksPath.spec.js
test/utils/isHookCreated.spec.js
test/utils/stubs.js

- read core.hooksPath from git config (if set)
- default to "process.cwd()/.git/hooks"
- adjust unit tests
Change how the path for git hooks is retrieved:
It now invokes `git config --get core.hooksPath` which provides a *relative* path (default to `.git/hooks` if unset), then create/delete the hooks at that path.
NOTE: @carloscuesta, the previous `git rev-parse` command returned an absolute folder.
Not sure if it is worth defaulting to that command, in case `core.hooksPath` is not set? (to be fully 100% backward-compatible?)
(I do not know if people would try to set-up gitmoji outside of the current working directory, feels edge-case to me 🤷‍♂️)
Issue: #577

:sparkles: update hooks create & delete path

---

.github/workflows/release.yaml
package.json

Hello! 👋🏼 
This PR automates the process of publishing the package to the `npm` registry. Every time that a new tag `v*` is pushed to the repository, automatically the `release.yml` github workflow will start to publish the package to the registry.
Related with #577

🔧 Automate npm publish with a GitHub Action

---

src/utils/getAbsoluteHooksPath.js
test/utils/getAbsoluteHooksPath.spec.js

🐛 Fix `getAbsoluteHooksPath` error

---

.github/workflows/ci.yml
package.json

This is required as #584 
Node.js v10 is coming to EOL next month

🔧 Bump minimum required Node version to `v12`

---

src/commands/config/prompts.js
src/utils/configurationVault.js
src/utils/getEmojis.js
test/utils/__snapshots__/configurationVault.spec.js.snap
test/utils/configurationVault.spec.js
test/utils/getEmojis.spec.js

`gitmoji.dev` is not accessible in some regions such as China. See Issue: [network](https://github.com/carloscuesta/gitmoji-cli/issues?q=network).
I think it is necessary to allow custom `GITMOJIS_URL`, so that users can even define their own desired list.
For example, use`https://raw.githubusercontent.com/carloscuesta/gitmoji/master/src/data/gitmojis.json` instead of `https://gitmoji.dev/api/gitmojis`.

🔧 Add gitmojis url config

---

README.md
package.json
src/cli.js
src/commands/commit/index.js
src/commands/commit/prompts.js
src/constants/commit.js
src/constants/flags.js
src/utils/findGitmojiCommand.js
src/utils/getDefaultCommitContent.js
test/commands/commit.spec.js
test/utils/findGitmojiCommand.spec.js
test/utils/getDefaultCommitContent.spec.js

This PR introduces the possibility of passing options to the `commit` and `hook` commands:
- `--title`
- `--message`
- `--scope`
Example usage:
```
$ gitmoji -c --title="Commit title" --message="Commit message" --scope="SCOPE-123"
```
The feature is intended for "advanced" users who might want to not introduce the prompts on the "interactive" prompt part.
Fixes #465 
https://user-images.githubusercontent.com/7629661/128042792-007bd989-04cf-4572-a13c-6c9c77f4c0b2.mov

✨ Introduce option flags for `commit` commands

---

src/commands/commit/withClient/index.js
test/commands/commit.spec.js

This PR improves the UX of the errors printed to the console when using the `commit` command in client mode
Fixes #610

🚸 Improve `commit` command errors output

---

src/commands/config/index.js
test/commands/config.spec.js
test/commands/stubs.js

Thanks to [🔧 Add gitmojis url config by YunYouJun · Pull Request #640](https://github.com/carloscuesta/gitmoji-cli/pull/640), you can custom `GITMOJIS_URL`.
But It didn't seem to be working.

🐛 Custom gitmojis url was not set

---

src/commands/commit/withClient/index.js
test/commands/commit.spec.js

Support streaming of stdout/stderr while using `gitmoji -c`, quite important when using pre-commit hook
Issue: https://github.com/carloscuesta/gitmoji-cli/issues/291
notes on tests:
developing the feature was quite easy, the very difficult part that I didn't crack yet, is testing, when using buffer stream we are not using `console.log` anymore, meaning tests like: https://github.com/carloscuesta/gitmoji-cli/blob/edf1f3b9081e259311af1da03b288e182b1a101e/test/commands/commit.spec.js#L53 
becomes impossible to implement, as Jest is not  able to mock `process.stdout`: https://github.com/facebook/jest/issues/9984
One possible mitigation was to listen on execa stream and use console.log on data events, but the compromise is that each line printed by the pre-commit hook is added a line carriage …

✨ Support stdout streaming

---

src/commands/commit/withClient/index.js
test/commands/commit.spec.js

If commit fails to execute, cli prints command so it can be copy / paste without executing again gitmoji-cli.
Updated the tests too.
Issue: #680

Print Git command if it failed

---

src/commands/commit/withHook/index.js
test/commands/commit.spec.js

✅  add test
cancel hook when automerge by git pull.
add check commitMessageSource equas 'merge' in commands/commit/withHook/index.js#cancelIfAmending function
Issue: #782
- [ ✅ ] All tests passed.

🐛 cancel hook when automerge by git pull

---

package.json

The Node.js minimum required version for this package was bumped some time ago, we can bump the babel preset env target version to 12.

🔧 Update babel/preset-env target node version 12

---

package.json
yarn.lock

This PR bumps the version of "execa" so it matches the functionality used.
In https://github.com/carloscuesta/gitmoji-cli/blob/master/src/commands/commit/withClient/index.js#L45 the `error.escapedCommand` is used to render the failed git command.
However, this property is not added until execa v5.1.0: https://github.com/sindresorhus/execa/releases/tag/v5.1.0
As such, the commit command funcitonality was "broken" with release https://github.com/carloscuesta/gitmoji-cli/releases/tag/v4.10.0 where dependency versions were made fixed.
Issue: No issue created

[Dependencies] Bump execa

---

.github/workflows/ci.yml
package.json

Hey! 👋🏼 
This PR bumps the minimum required node version to `v14`.

💥Bump Node.js minimum required version to `14.x`

---

README.md

Allow users to copy shell commands using GitHubs code block copy button without needing to remove the shell character on paste.
Since GitHub has now has a copy button on code bock fields, it makes to avoid prepending shell commands with the `$` shell character. Users have to manually remove the character if they want to copy-paste the commands into their CLI.
This is mainly to make installing easier for users. But, removed it on all code blocks to avoid confusion around inconsistency.
Btw love gitmoji, I use it basically every day on all my projects.

Remove $ shell character from README CLI commands

---

.github/workflows/release.yaml

This PR updates the `node-version` of the `release` action to `16` and updates the publish authentication method.

👷 Update npm publish workflow

---

.flowconfig
jsconfig.json
package.json
src/cli.js
src/commands/commit/index.js
src/commands/commit/prompts.js
src/commands/commit/withClient/index.js
src/commands/config/index.js
src/commands/config/prompts.js
src/commands/hook/create/index.js
src/commands/hook/remove/index.js
src/commands/list/index.js
src/commands/search/index.js
src/commands/update/index.js
src/utils/configurationVault.js
src/utils/filterGitmojis.js
src/utils/findGitmojiCommand.js
src/utils/getDefaultCommitContent.js
src/utils/isHookCreated.js
test/commands/commands.spec.js
test/commands/commit.spec.js
test/commands/config.spec.js
test/commands/hook.spec.js
test/commands/list.spec.js
test/commands/search.spec.js
test/commands/update.spec.js
yarn.lock

Hey! 👋🏼 
This PR replaces `./` imports with the `babel-plugin-module-resolver` so we can import everything using `@`.

♻️ Use `babel-plugin-module-resolver` for imports

---

README.md
src/commands/commit/withClient/index.js
src/commands/config/index.js
src/commands/config/prompts.js
src/utils/configurationVault.js
test/commands/commit.spec.js
test/commands/config.spec.js
test/utils/__snapshots__/configurationVault.spec.js.snap
test/utils/configurationVault.spec.js

Hey! 👋🏼 
This PR removes the `signedCommit` option from the cli as this can be controlled with `.gitconfig`:
```
$ git config --global commit.gpgsign true
```

🔥 Remove signed commits option from configuration

---

README.md

- There is a typo in the README.md and it has been corrected, so please check if it is OK.
- Commas were misplaced in the example description of package.json in README.md.
I didn't create an issue for fixing typos

✏️ Fix comma typo in README.md 

---

src/utils/configurationVault/getConfiguration.js
test/commands/commit.spec.js
test/utils/buildFetchOptions.spec.js
test/utils/configurationVault/getConfiguration.spec.js

1. Migrate from `require` to `readFileSync` as described in https://github.com/carloscuesta/gitmoji-cli/pull/926#pullrequestreview-1122464804.
2. Migrate from `require` to `import` statements for `mockProcessExit` in unit tests.
3. Migrate from `require` to dynamic `import` for `buildFetchOptions` unit tests.

♻️ Migrate from require to readFileSync in configurationVault

---

package.json
yarn.lock

Hey!
Finally `inquirer-autocomplete-prompt` was updated to support `inquirer@9` which means we can update to the last version of the library 😊

⬆️ Bump inquirer dependencies

---

src/commands/commit/withClient/index.js
test/commands/commit.spec.js

This PR adjusts the command sent for `gitmoji -c` when the `automatically add` is enabled.
Before: if the command failed, it would return a retry command without the `a` preventing the very simply copy+paste to resume after a failure.
Now it will return that in the error when that setting is enabled.

🚸 Improve error message when doing commits

---

.github/workflows/ci.yml
package.json

Hey! 👋🏼 
Node.js v14 end of life is coming soon and we need to bump the requirements for the `cli`.

💥 Bump minimum `node` version to `>=16`

---

package.json

Bumping the version to release `gitmoji-cli` v8.0.0, to be merged after Dependabot PR's tomorrow 🙏🏼

🔖 Bump version

---

src/commands/hook/hook.js
test/commands/__snapshots__/hook.spec.js.snap

with the -c option the cmd and the args must be within quotes
With #1039 and the `-c` option the needed quotes for `-c` are missing
Issue: #

:bug: (hooks) fix bug for npx -c call

---

src/cli.js
src/utils/findGitmojiCommand.js
test/__snapshots__/cli.spec.js.snap
test/utils/findGitmojiCommand.spec.js
test/utils/stubs.js

This PR introduces the usage of subcommands alongside the usual flags. This means now eg. `gitmoji commit` is now usable as well as `gitmoji -c`.
Issue: #1070

✨ Expose flags as subcommands

---

src/commands/commit/prompts.js
src/commands/config/index.js
src/commands/config/prompts.js
src/constants/configuration.js
src/utils/configurationVault/getConfiguration.js
src/utils/configurationVault/index.js
test/commands/__snapshots__/commit.spec.js.snap
test/commands/commit.spec.js
test/commands/config.spec.js
test/commands/stubs.js
test/utils/configurationVault/__snapshots__/defaults.spec.js.snap
test/utils/configurationVault/defaults.spec.js
test/utils/configurationVault/getConfiguration.spec.js
test/utils/configurationVault/vault.spec.js

This PR updates the configuration vault, adding new functions to manage message and scope prompts. Most of the time you don't need a commit body and only need the title for quick commits. So to improve UX allow the user to disable that option so it only prompts for a gitmoji and title.

✨ Allow user to disable message prompt

---

src/commands/commit/prompts.js
src/commands/commit/withClient/index.js
src/commands/commit/withHook/index.js

Didn't think about checking the code flow coming after the prompts but apparently we're still writing `undefined` to the message body if the prompt didn't pass anything. So now we only include the message body if it was provided in the prompt.

🚑 Don't include `undefined` in message body

---

README.md
src/commands/commit/index.js
src/commands/commit/prompts.js
src/commands/config/index.js
src/commands/config/prompts.js
src/constants/configuration.js
src/utils/configurationVault/getConfiguration.js
src/utils/configurationVault/index.js
test/commands/config.spec.js
test/commands/stubs.js
test/utils/configurationVault/__snapshots__/defaults.spec.js.snap
test/utils/configurationVault/getConfiguration.spec.js
test/utils/configurationVault/vault.spec.js

I believe that the recently merged [capitalize feature](https://github.com/carloscuesta/gitmoji-cli/pull/1071) should be configurable through the static config file.
For instance, the [`Conventional Commits`](https://www.conventionalcommits.org/en/v1.0.0/#are-the-types-in-the-commit-title-uppercase-or-lowercase) standard does not mandate capitalizing the first letter of commit titles, but recommends maintaining consistency. However, it would be challenging to maintain consistency if lowercase titles were the default with this modification.
This pull request is addressing that issue. What is your opinion on it?

✨ Allow user to disable capitalized titles

---

src/cli.js
src/commands/search/index.js
src/utils/findGitmojiCommand.js
test/cli.spec.js
test/commands/search.spec.js
test/utils/findGitmojiCommand.spec.js
test/utils/stubs.js

With the introduction of the subcommand when you use `gitmoji search bug linter` it will always include the `search` keyword in the query which is a regression. This PR ensures the `search` input is filtered out of `cli.input` when the command is executed through a subcommand.
It changes how the `search` command is handled. Instead of going over each input from within `cli.js` we now determine it in `findGitmojiCommand` and pass the correct option to the command depending on the situation. Where it is then further handled by the `search` command itself.

🐛 Filter out `search` from query when using subcommands

---

src/cli.ts

This PR updates the imports from static imports to dynamic imports which should result in some easy speed improvements.
- Improved startup speed by utilising dynamic imports for each command only when they are needed. This improves the initial startup time because it doesn't have to load in all the other commands that are unused.
- https://github.com/carloscuesta/gitmoji-cli/issues/1108

:zap: Use dynamic imports instead of static imports

---

package.json
src/utils/buildFetchOptions.js
test/utils/buildFetchOptions.spec.js
yarn.lock

- Upgraded proxy-agent package to 6.3.1
- Removed proxy url parameter, as it was only used in tests
- Modified existing tests to work with new proxy agents data structure
- Removed tests for proxy url as argument
Issue: #1193

:arrow_up: Upgrade proxy-agent to v.6

---

src/cli.ts

Hey! 👋🏼 
This addresses a breaking change that was introduced on the last update of meow.

🚚 Rename `alias` to `shortFlag` in `cli` for `meow`

---

.github/workflows/ci.yml
package.json

💥 Bump Node.js minimum version to `v18`

---

src/commands/commit/prompts.js

When you type a commit message, on the 10nth char, the text move one character to the right because the prompt title goes from `9/48` to `10/48`
```diff
- Enter the commit title [9/48]: 123456789
+ Enter the commit title [10/48]: 1234567890
```
This is pretty annoying, so a added a `padStart(2)` to avoid this effect
```diff
- Enter the commit title [09/48]: 123456789
+ Enter the commit title [10/48]: 1234567890
```
There will still be the same effect after 99, but it's an un-recommended number of chars, so we might ignore this.

✨ Avoid text moving when nb char is 10

---

.flowconfig
babel.config.json
package.json
src/cli.ts
src/commands/commit/withClient/index.ts
test/__snapshots__/cli.spec.ts.snap
test/cli.spec.ts
tsconfig.json

After reading reports from people trying their hand on converting files to TS, I noticed the setup wasn't fully allowing conversion without causing a big waterfall of required changes. While it was already possible to import Flow files into TS, it apparently wasn't yet possible to import TS files into Flow without the need for a lot of changes. This PR basically attempts to fix whatever was needed so proper TS work can start again 🚀
- Adjusted `babel` to properly handle all `.ts` files and not just the ones in `./src`
- Adjusted `tsconfig.json` to properly output ESM so it can be used alongside other ESM modules like `meow` and `execa`
- `withClient.ts` has been converted to TS 
- Jest now properly looks for `.ts` files and includes them in the test run
- `cli.spec.ts` has not been …

♻️ Maintenance: Improve TypeScript support

---

package.json
yarn.lock

Seems like `inquirer` unified their monorepo setup and changed from a `lib` directory to `src` which is causing `inquirer-autocomplete-prompt` to fail since it has a peer dependency on an older version of `inquirer`. Package managers are bumping the version to `9.3.x` due to us having `^9.2.23`.
So we limit package managers to not update to minor version `9.3.x` for now. 
Issue: https://github.com/carloscuesta/gitmoji-cli/issues/1321

📌 Limit inquirer to patch versions

---

src/commands/commit/withClient/index.ts
test/commands/commit.spec.js
test/commands/stubs.js

Fixes https://github.com/carloscuesta/gitmoji-cli/issues/1391. Not sure if this ever reported with quotes around the message but `execa` seems to automatically escape quotes and at one point it stopped working. 
- Added `shell: true` option to git commit execution
- Updated commit message formatting to include quotes around both title and message parts
- Modified test stubs and expectations to match the new quoted format

:bug: Explicit wrap messages with quotes
