carloscuesta/gitmoji-cli

- src/gitmoji.js
Improving Search functionality by better matching suggestions
Signed-off-by: me-shaon <shaon.cse81@gmail.com>
> :zap: Improving Search functionality by better matching suggestions

- cli.js
- src/gitmoji.js
- test/test.js
Add the -version option
Issue: #13
> Add version option

- package.json
- src/gitmoji.js
- yarn.lock
Add search functionality when commiting
Using [inquirer-autocomplete-prompt](https://github.com/mokkabonna/inquirer-autocomplete-prompt) for the autocompletion
Issue: #30
> Autocomplete for interactive client

- src/gitmoji.js
> 🐛 Fix code injection

- package.json
- src/gitmoji.js
- yarn.lock
I added the check of parent directories for `.git` folder to allow commiting from from a sub folder of a repo, like a regular commit.
Issue: #55 
Thanks ✌️
> ✨  Allow commit in sub directory

- src/gitmoji.js
> 🐛 Fix gitmoji commit hook creation on Windows

- README.md
- cli.js
I think It's a better way to show options in command line.
> :art: Improving style of Options

- cli.js
Issue: #67 
This PR removes default behaviour from running `gitmoji`
> 🐛 Fix cli flags

- README.md
> 📝  Add codesponsor

- package.json
- src/config.js
- src/constants.js
- src/gitmoji.js
- src/prompts.js
- test/__snapshots__/gitmojiCli.spec.js.snap
- test/gitmojiCli.spec.js
- test/stubs.js
- Added default signed commit option in <gitmoji -g>
- Use constants in GitmojiCli `config()`
Issue: #56
> Add signed config

- package.json
- yarn.lock
> ☂️ Add codecov

- .gitignore
- README.md
- src/config.js
- src/gitmoji.js
- src/guard.js
- src/prompts.js
- test/__snapshots__/gitmojiCli.spec.js.snap
- test/gitmojiCli.spec.js
- test/stubs.js
- Add a guard module that validates the user input from inquirer.js instead of checking it at the prompts.
> Add guard and improve coverage

- cli.js
- src/guard.js
- src/utils.js
- test/gitmojiCli.spec.js
- test/stubs.js
> ♻️ Cli refactor and improvements

- src/constants.js
- test/__snapshots__/gitmojiCli.spec.js.snap
From [POSIX standard](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206):
> 3.206 Line
> A sequence of zero or more non- <newline> characters plus a terminating <newline> character.
> Lines should be terminated by a newline character

- src/constants.js
- src/gitmoji.js
- test/__snapshots__/gitmojiCli.spec.js.snap
Use `git rev-parse --absolute-git-dir` to find `.git/` folder
Issue: #86
> Create hook from anywhere in git repo

- src/gitmoji.js
> Improve defaults of AutoAdd and SignedCommit (issue #176)

- README.md
- src/config.js
- src/constants.js
- src/gitmoji.js
- src/guard.js
- src/prompts.js
- test/__snapshots__/gitmojiCli.spec.js.snap
- test/gitmojiCli.spec.js
- test/stubs.js
> ♻️ Reference prompt and setting

- src/gitmoji.js
- src/guard.js
- src/prompts.js
- test/__snapshots__/gitmojiCli.spec.js.snap
- test/gitmojiCli.spec.js
- test/stubs.js
Added the option to enter scope of changes in a particular commit. The scope is wrapped in parenthesis ( just like the [commitizen](https://github.com/commitizen/cz-cli) tool provides for more making commit messages more informative and useful.
Issue: #138
> Add scope feature

- src/gitmoji.js
> ✨ Improve fetching emojis process

- .github/ISSUE_TEMPLATE.md
Issue template file had an error in line 6, instead of "your", it was written "yor"
Issue: None
> 💬 Correcting issue template

- package.json
- yarn.lock
> ⬆️ Bump babel dependencies

- .github/workflows/release.yaml
- .gitignore
- package.json
- yarn.lock
This PR adds automated builds of the CLI to releases on GitHub using [`pkg`](https://github.com/vercel/pkg). Binary builds allow users without Node.js and npm to use the CLI without installing other software.
> 👷 (build): Add binary build & release on GitHub.

- .travis.yml
- package.json
- src/utils/installMessage.js
Just trying to make Open Source more sustainable
> ❤️  Add postinstall messsage

- package.json
- src/commands/search/index.js
- src/utils/filterGitmojis.js
- test/commands/commit.spec.js
- test/utils/__snapshots__/filterGitmojis.spec.js.snap
- test/utils/filterGitmojis.spec.js
- yarn.lock
> ⬆️  Bump fuse.js to 6.x.x

- README.md
Mention the option to install gitmoji via brew, which is easier if you are already using it
Issue: N/A
No code change
> Add brew as an install method

- README.md
> 📝 Write docs for configuration options

- src/utils/getEmojis.js
This implements the emoji fetching from the Gitmoji API: https://github.com/carloscuesta/gitmoji/pull/713
This fixes #552
> 🐛 Use Gitmoji API instead of GitHub Raw 

- package.json
- src/utils/buildFetchOptions.js
- src/utils/getEmojis.js
- test/utils/buildFetchOptions.spec.js
- test/utils/getEmojis.spec.js
- yarn.lock
Add proxy agent for node-fetch behind a proxy
Issue: #579
> Add proxy support for node-fetch

- package.json
- src/utils/getEmojis.js
- test/utils/getEmojis.spec.js
> ✨ Update command prints updated emojis

- package.json
- yarn.lock
This reverts commit 3cb4e36c0bcaa44fb5fdd64d899acd7cdd7d0e47.
Issue: #672
> ⏪️ :arrow_up: Bump ora from 5.4.1 to 6.0.0 (#669)"

- README.md
> 📝 Improve gitmoji-cli commit mode docs

- .flowconfig
- package.json
- yarn.lock
> 📌 Pin `dependencies` and `devDependencies`

- package.json
- yarn.lock
Updates node-fetch version to 2.6.7
Issue: #812
> :arrow_up: Updates node-fetch to v2.6.7

- .flowconfig
- package.json
- src/cli.js
- src/commands/commit/index.js
- src/commands/commit/withClient/index.js
- src/commands/commit/withHook/index.js
- src/commands/config/prompts.js
- src/commands/list/index.js
- src/commands/search/index.js
- src/commands/update/index.js
- src/constants/flags.js
- src/utils/buildFetchOptions.js
- src/utils/configurationVault.js
- src/utils/emojisCache.js
- src/utils/filterGitmojis.js
- src/utils/findGitmojiCommand.js
- src/utils/isHookCreated.js
- src/utils/printEmojis.js
- yarn.lock
Bump `flow-bin` to the latest version
> ⬆️ Bump `flow-bin`

- README.md
- src/commands/commit/withClient/index.js
- test/commands/commit.spec.js
- test/utils/buildFetchOptions.spec.js
I applied recommendations based on the following tools:
* https://github.com/codespell-project/codespell
* https://github.com/crate-ci/typos
I didn't create an issue for fixing typos
> ✏️ Fix some typos in the code

- .github/workflows/release.yaml
Hey! :wave:
This PR updates the `release` workflow to automatically generate changelogs
> ♻️ Update release workflow

- src/utils/configurationVault.js
Hey! 👋🏼 
This PR introduces a schema to validate the configuration set by `conf`.
> ♻️ Add `schema` to `configVault`

- src/utils/configurationVault/getConfiguration.js
> 🐛 Fix `getConfiguration.get` default values

- src/commands/commit/guard.js
- src/commands/commit/prompts.js
- test/commands/__snapshots__/commit.spec.js.snap
- test/commands/commit.spec.js
This PR enables using backticks as part of the message&title prompts
Fixes #878
> ✨ Allow backtick characters

- package.json
- src/commands/config/guard.js
- src/commands/config/prompts.js
- test/commands/__snapshots__/config.spec.js.snap
- test/commands/config.spec.js
- test/commands/stubs.js
- yarn.lock
> ✨ Validate `GITMOJI_URL` configuration prompt

- src/utils/configurationVault/getConfiguration.js
> ✨ Update configuration fallbacks

- .github/workflows/ci.yml
- .github/workflows/release.yaml
Hey! 👋🏼 
This PR updates the `actions/setup-node` version.
> ⬆️ Update `actions/setup-node`

- .github/workflows/ci.yml
- .gitignore
- package.json
- turbo.json
- yarn.lock
Setting up turbo repo to speed up builds
> ✨ Setup turborepo 

- .github/workflows/lock.yml
Hey! 👋🏼 
This issue adds a GitHub action to automatically lock and solve the conversations on old issues and threads
> 👷 Add `lock` action for old threads

- package.json
- yarn.lock
> ⬆️ Bump `babel-plugin-module-resolver`

- src/commands/commit/index.js
- src/commands/commit/prompts.js
This PR improves the commit message creation process by ensuring that the title is capitalized.
Issue: #1067
> ✨ Always capitalise the first letter of the commit message

- src/commands/hook/hook.js
- test/commands/__snapshots__/hook.spec.js.snap
Issue: Fixes https://github.com/carloscuesta/gitmoji-cli/issues/1084
> 🐛 Fix `hook` shebang

- package.json
- src/commands/commit/withClient/index.js
- src/utils/configurationVault/index.js
- src/utils/getEmojis.js
- yarn.lock
Hey! 👋🏼 
This PR setups ESLint.
> 👨‍💻 Setup ESLint

- src/commands/commit/index.js
- src/commands/commit/prompts.js
- src/commands/commit/withHook/index.js
- test/commands/commit.spec.js
- test/commands/stubs.js
Hey! 👋🏼 
Fixes https://github.com/carloscuesta/gitmoji-cli/issues/1037
> ✨ Skip `hook` if gitmoji is found

- .github/workflows/ci.yml
- package.json
Hey! 👋🏼 
This PR switches to the codecov uploader and removes the deprecated module.
> ♻️ Use codecov uploader
